#pragma once

#define BULBTILS_STRINGIFY_IMPL(x) #x
#define BULBTILS_STRINGIFY(x) BULBTILS_STRINGIFY_IMPL(x)

#define BULBTILS_VERSION_MAJOR 1
#define BULBTILS_VERSION_MINOR 0
#define BULBTILS_VERSION_PATCH 0
#define BULBTILS_VERSION_SUFFIX "-pre"

#define BULBTILS_VERSION_STRING \
	BULBTILS_STRINGIFY(BULBTILS_VERSION_MAJOR) "." \
	BULBTILS_STRINGIFY(BULBTILS_VERSION_MINOR) "." \
	BULBTILS_STRINGIFY(BULBTILS_VERSION_PATCH) \
	BULBTILS_VERSION_SUFFIX